- hosts: bind
  vars:
    domain: example.com
    cluster_name: mycluster
    network: "192.168.100"
    rev_domain: "100.168.192.in-addr.arpa"
  tasks:
    - name: Install pkgs
      yum:
        name:
          - bind
          - bind-utils
        state: present

    - name: Copy named conf file
      template:
        src: templates/named.conf.j2
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0660
      notify: restart bind

    - name: Make named directory
      file:
        path: /etc/named
        state: directory
        owner: root
        group: named
        mode: 0750

    - name: Copy named conf local file
      template:
        src: templates/named.conf.local.j2
        dest: /etc/named/named.conf.local
        owner: root
        group: named
        mode: 0640
      notify: restart bind


    - name: Make zones Directory
      file:
        path: /etc/named/zones
        state: directory
        owner: root
        group: named
        mode: 0750

    - name: Copy forward file
      template:
        src: templates/db.forward.j2
        dest: /etc/named/zones/db.{{ domain }}.db
        owner: root
        group: named
        mode: 0640
      notify: restart bind

    - name: Copy reverse file
      template:
        src: templates/db.reverse.j2
        dest: /etc/named/zones/db.{{ domain }}.reverse.db
        owner: root
        group: named
        mode: 0640
      notify: restart bind

  handlers:
    - name: restart bind 
      service:
        name: named
        state: restarted

